<?php
/**
 * @file
 * Code for the Teaser-content feature.
 */

include_once 'teaser_content.features.inc';



function cambridge_theme_field__field_item_1_image($variables) {

$link = $variables['element']['#object']->field_item_1_link['und'][0]['url'];
$text = $variables['element']['#object']->field_item_1_text['und'][0][safe_value];
$image = drupal_render($variables['items'][0]);
      return _teaser_content_cht($link,$text,$image);
}


function _teaser_content_cht($link,$text,$image) {

$output= '<div class="campl-column6">
<div class="campl-content-container campl-horizontal-teaser-img">
<a href="' . $link .'" class="campl-teaser-img-link">
' . $image . ' </a></div>
</div>
<div class="campl-column6"><div class="campl-content-container campl-horizontal-teaser-txt"><h3 class="campl-teaser-title">
<a href="' . $link .'">' . $text .'
<a href="' . $link .'" class="campl-primary-cta">Read more</a></div></div> ';

  return $output;
}




/**
 * Implements hook_theme_registry_alter().
 */
function teaser_content_theme_registry_alter(&$theme_registry) {
  $extension   = '.tpl.php';
  $module_path = drupal_get_path('module', 'teaser_content');
  $files       = file_scan_directory($module_path . '/templates', '/' . preg_quote($extension) . '$/');
  foreach ($files as $file) {
	$template = drupal_basename($file->filename, $extension);
	$theme    = str_replace('-', '_', $template);
	list($base_theme, $specific) = explode('__', $theme, 2);


	// Don't override base theme.
	if (!empty($specific) && isset($theme_registry[$base_theme])) {
	  $theme_info = array(
		'template'   => $template,
		'path'       => drupal_dirname($file->uri),
		'variables'  => $theme_registry[$base_theme]['variables'],
		'base hook'  => $base_theme,
		// Other available value: theme_engine.
		'type'       => 'module',
		'theme path' => $module_path,
	  );


	  $theme_registry[$theme] = $theme_info;
	}
  }
}