<?php
/**
 * @file
 * Code for the Teaser-content feature.
 */

include_once 'teaser_content.features.inc';



function cambridge_theme_field__field_item_1_image($variables) {

$link = $variables['element']['#object']->field_item_1_link['und'][0]['url'];
$text = $variables['element']['#object']->field_item_1_text['und'][0]['safe_value'];
$image = drupal_render($variables['items'][0]);

      $output = _teaser_content_col1(); // need to close div...
      $output .=  _teaser_content_cht($link,$text,$image);
      $output .= _teaser_content_divider();
      return $output;
}

function cambridge_theme_field__field_item_2_image($variables) {
$link = $variables['element']['#object']->field_item_2_link['und'][0]['url'];
$text = $variables['element']['#object']->field_item_2_text['und'][0]['safe_value'];
$image = drupal_render($variables['items'][0]);

      $output =  _teaser_content_cht($link,$text,$image);
      $output .= _teaser_content_divider();
      return $output;
}


function cambridge_theme_field__field_item_3_image($variables) {

$link = $variables['element']['#object']->field_item_3_link['und'][0]['url'];
$text = $variables['element']['#object']->field_item_3_text['und'][0]['safe_value'];
$image = drupal_render($variables['items'][0]);

      $output =  _teaser_content_cht($link,$text,$image);
      $output .= _teaser_content_divider();

      return $output;
}


function cambridge_theme_field__field_item_4_image($variables) {

$link = $variables['element']['#object']->field_item_4_link['und'][0]['url'];
$text = $variables['element']['#object']->field_item_4_text['und'][0]['safe_value'];
$image = drupal_render($variables['items'][0]);


      $output =  _teaser_content_cht($link,$text,$image);
      $output .= '</div></div></div>'; // close div from item 1
      return $output;
}

function cambridge_theme_field__field_item_5_image($variables) {

$link = $variables['element']['#object']->field_item_5_link['und'][0]['url'];
$text = $variables['element']['#object']->field_item_5_text['und'][0]['safe_value'];
$image = drupal_render($variables['items'][0]);

      $output =	_teaser_content_col2();	// need	to close div...
      $output .=  _teaser_content_cvt($link,$text,$image);
      $output .= _teaser_content_divider_lb();
      return $output;
}


function cambridge_theme_field__field_item_6_image($variables) {

$link = $variables['element']['#object']->field_item_6_link['und'][0]['url'];
$text = $variables['element']['#object']->field_item_6_text['und'][0]['safe_value'];
$image = drupal_render($variables['items'][0]);

      $output =  _teaser_content_cvt($link,$text,$image);
      $output .= '</div>';
      return $output;
}







function _teaser_content_cvt($link,$text,$image) {

$output= '
<!-- CVT -->
<div class="campl-content-container campl-sub-column-left-border">
<div class="campl-vertical-teaser campl-teaser">
<div class="campl-content-container campl-vertical-teaser-img">
<a href="' . $link .'" class="campl-teaser-img-link">
' . $image . ' </a></div>
</div>
<div class="campl-content-container campl-vertical-teaser-txt">
' . $text .'
<a href="' . $link .'" class="campl-primary-cta">Read more</a></div></div>
<!-- end CVT -->';

  return $output;
}



function _teaser_content_col1() {
	 $col1= '<div class="campl-column9 campl-main-content" style="min-height: 1200px;">';
	 return $col1;
}

function _teaser_content_col2() {
	 $col2 = '</div><!-- end col1 _col2 fn -->
<div class="campl-column3">';
	 return $col2;
}

function _teaser_content_divider_lb() {
	 $div ='<div class="campl-column12">
<div class="campl-side-padding campl-content-container campl-sub-column-left-border">
<hr class="campl-teaser-divider">
</div>
</div>';

	return $div;
}

function _teaser_content_divider() {

     $div = '
<!-- _teaser_content_divider() -->
<div class="campl-column12"><div class="campl-side-padding campl-content-container"><hr class="campl-teaser-divider"</div></div>
<!-- end _teaser_content_divider() -->';
     return $div;

}



function _teaser_content_cht($link,$text,$image) {

$output= '
<!-- CHT -->
<div class="campl-content-container">
<div class="campl-column6">
<div class="campl-content-container campl-horizontal-teaser-img">
<a href="' . $link .'" class="campl-teaser-img-link" style="margin-bottom:20px;;">
' . $image . ' </a></div>
</div>
<div class="campl-column6"><div class="campl-content-container campl-horizontal-teaser-txt">
'. $text .' <a href="' . $link .'" class="campl-primary-cta" style="margin-bottom: 10px;">Read more</a></div></div></div>
<!-- end CHT -->';

  return $output;
}




/**
 * Implements hook_theme_registry_alter().
 */
function teaser_content_theme_registry_alter(&$theme_registry) {
  $extension   = '.tpl.php';
  $module_path = drupal_get_path('module', 'teaser_content');
  $files       = file_scan_directory($module_path . '/templates', '/' . preg_quote($extension) . '$/');
  foreach ($files as $file) {
	$template = drupal_basename($file->filename, $extension);
	$theme    = str_replace('-', '_', $template);
	list($base_theme, $specific) = explode('__', $theme, 2);

	$var = (isset($theme_registry[$base_theme]['variables']) ? $theme_registry[$base_theme]['variables'] : false);
	// Don't override base theme.
	if (!empty($specific) && isset($theme_registry[$base_theme])) {
	  $theme_info = array(
		'template'   => $template,
		'path'       => drupal_dirname($file->uri),
		'variables'  => $var,
		'base hook'  => $base_theme,
		// Other available value: theme_engine.
		'type'       => 'module',
		'theme path' => $module_path,
	  );


	  $theme_registry[$theme] = $theme_info;
	}
  }
}